# http://clouds.freeideas.cz/subdom/clouds/2017/07/26/ansible-install-docker-ce/
- name: main
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: install docker
    include: install-docker.yml

  - name: install fail2ban
    include: install-fail2ban.yml

  - name: copy openvpn config
    copy:
      src: ../config/openvpn
      dest: /etc/

  - name: install scheduling
    include: install-scheduling.yml

  - name: change sshd to not allow passwords
    command: sed -i -e s/#PasswordAuthentication\ yes/PasswordAuthentication\ no/ /etc/ssh/sshd_config

  - name: restart sshd
    service:
      name:  sshd
      state: restarted